#!/bin/sh

useradd student -p $(echo student | openssl passwd -stdin -1) -G wheel
useradd student -G vagrant
usermod root -p $(echo redhat | openssl passwd -stdin -1)

yum install -y bash-completion bash-completion-extra

systemctl enable firewalld.service
systemctl start firewalld.service

yum install -y rng-tools
rngd -r /dev/urandom
